export const LOGIN = "login"
export const FORGOT_PASSWORD = "forgotPassword"
export const SETTING = "setting"
export const HOME_PAGE = "home_page"
export const CMS_PAGE = "pages"
export const SUBMIT_CONTACT_REQUEST = "contactUs"
