<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(
            array('id' => 1,'code' => 'AF' ,'name' => "Afghanistan",'phonecode' => 93,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 2,'code' => 'AL' ,'name' => "Albania",'phonecode' => 355,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 3,'code' => 'DZ' ,'name' => "Algeria",'phonecode' => 213,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 4,'code' => 'AS' ,'name' => "American Samoa",'phonecode' => 1684,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 5,'code' => 'AD' ,'name' => "Andorra",'phonecode' => 376,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 6,'code' => 'AO' ,'name' => "Angola",'phonecode' => 244,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 7,'code' => 'AI' ,'name' => "Anguilla",'phonecode' => 1264,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 8,'code' => 'AQ' ,'name' => "Antarctica",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 9,'code' => 'AG' ,'name' => "Antigua And Barbuda",'phonecode' => 1268,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 10,'code' => 'AR','name' => "Argentina",'phonecode' => 54,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 11,'code' => 'AM','name' => "Armenia",'phonecode' => 374,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 12,'code' => 'AW','name' => "Aruba",'phonecode' => 297,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 13,'code' => 'AU','name' => "Australia",'phonecode' => 61,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 14,'code' => 'AT','name' => "Austria",'phonecode' => 43,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 15,'code' => 'AZ','name' => "Azerbaijan",'phonecode' => 994,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 16,'code' => 'BS','name' => "Bahamas The",'phonecode' => 1242,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 17,'code' => 'BH','name' => "Bahrain",'phonecode' => 973,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 18,'code' => 'BD','name' => "Bangladesh",'phonecode' => 880,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 19,'code' => 'BB','name' => "Barbados",'phonecode' => 1246,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 20,'code' => 'BY','name' => "Belarus",'phonecode' => 375,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 21,'code' => 'BE','name' => "Belgium",'phonecode' => 32,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 22,'code' => 'BZ','name' => "Belize",'phonecode' => 501,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 23,'code' => 'BJ','name' => "Benin",'phonecode' => 229,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 24,'code' => 'BM','name' => "Bermuda",'phonecode' => 1441,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 25,'code' => 'BT','name' => "Bhutan",'phonecode' => 975,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 26,'code' => 'BO','name' => "Bolivia",'phonecode' => 591,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 27,'code' => 'BA','name' => "Bosnia and Herzegovina",'phonecode' => 387,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 28,'code' => 'BW','name' => "Botswana",'phonecode' => 267,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 29,'code' => 'BV','name' => "Bouvet Island",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 30,'code' => 'BR','name' => "Brazil",'phonecode' => 55,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 31,'code' => 'IO','name' => "British Indian Ocean Territory",'phonecode' => 246,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 32,'code' => 'BN','name' => "Brunei",'phonecode' => 673,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 33,'code' => 'BG','name' => "Bulgaria",'phonecode' => 359,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 34,'code' => 'BF','name' => "Burkina Faso",'phonecode' => 226,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 35,'code' => 'BI','name' => "Burundi",'phonecode' => 257,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 36,'code' => 'KH','name' => "Cambodia",'phonecode' => 855,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 37,'code' => 'CM','name' => "Cameroon",'phonecode' => 237,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 38,'code' => 'CA','name' => "Canada",'phonecode' => 1,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 39,'code' => 'CV','name' => "Cape Verde",'phonecode' => 238,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 40,'code' => 'KY','name' => "Cayman Islands",'phonecode' => 1345,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 41,'code' => 'CF','name' => "Central African Republic",'phonecode' => 236,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 42,'code' => 'TD','name' => "Chad",'phonecode' => 235,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 43,'code' => 'CL','name' => "Chile",'phonecode' => 56,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 44,'code' => 'CN','name' => "China",'phonecode' => 86,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 45,'code' => 'CX','name' => "Christmas Island",'phonecode' => 61,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 46,'code' => 'CC','name' => "Cocos (Keeling) Islands",'phonecode' => 672,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 47,'code' => 'CO','name' => "Colombia",'phonecode' => 57,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 48,'code' => 'KM','name' => "Comoros",'phonecode' => 269,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 49,'code' => 'CG','name' => "Congo",'phonecode' => 242,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 50,'code' => 'CD','name' => "Congo The Democratic Republic Of The",'phonecode' => 242,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 51,'code' => 'CK','name' => "Cook Islands",'phonecode' => 682,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 52,'code' => 'CR','name' => "Costa Rica",'phonecode' => 506,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 53,'code' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'phonecode' => 225,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 54,'code' => 'HR','name' => "Croatia (Hrvatska)",'phonecode' => 385,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 55,'code' => 'CU','name' => "Cuba",'phonecode' => 53,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 56,'code' => 'CY','name' => "Cyprus",'phonecode' => 357,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 57,'code' => 'CZ','name' => "Czech Republic",'phonecode' => 420,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 58,'code' => 'DK','name' => "Denmark",'phonecode' => 45,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 59,'code' => 'DJ','name' => "Djibouti",'phonecode' => 253,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 60,'code' => 'DM','name' => "Dominica",'phonecode' => 1767,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 61,'code' => 'DO','name' => "Dominican Republic",'phonecode' => 1809,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 62,'code' => 'TP','name' => "East Timor",'phonecode' => 670,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 63,'code' => 'EC','name' => "Ecuador",'phonecode' => 593,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 64,'code' => 'EG','name' => "Egypt",'phonecode' => 20,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 65,'code' => 'SV','name' => "El Salvador",'phonecode' => 503,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 66,'code' => 'GQ','name' => "Equatorial Guinea",'phonecode' => 240,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 67,'code' => 'ER','name' => "Eritrea",'phonecode' => 291,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 68,'code' => 'EE','name' => "Estonia",'phonecode' => 372,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 69,'code' => 'ET','name' => "Ethiopia",'phonecode' => 251,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 70,'code' => 'XA','name' => "External Territories of Australia",'phonecode' => 61,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 71,'code' => 'FK','name' => "Falkland Islands",'phonecode' => 500,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 72,'code' => 'FO','name' => "Faroe Islands",'phonecode' => 298,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 73,'code' => 'FJ','name' => "Fiji Islands",'phonecode' => 679,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 74,'code' => 'FI','name' => "Finland",'phonecode' => 358,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 75,'code' => 'FR','name' => "France",'phonecode' => 33,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 76,'code' => 'GF','name' => "French Guiana",'phonecode' => 594,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 77,'code' => 'PF','name' => "French Polynesia",'phonecode' => 689,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 78,'code' => 'TF','name' => "French Southern Territories",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 79,'code' => 'GA','name' => "Gabon",'phonecode' => 241,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 80,'code' => 'GM','name' => "Gambia The",'phonecode' => 220,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 81,'code' => 'GE','name' => "Georgia",'phonecode' => 995,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 82,'code' => 'DE','name' => "Germany",'phonecode' => 49,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 83,'code' => 'GH','name' => "Ghana",'phonecode' => 233,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 84,'code' => 'GI','name' => "Gibraltar",'phonecode' => 350,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 85,'code' => 'GR','name' => "Greece",'phonecode' => 30,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 86,'code' => 'GL','name' => "Greenland",'phonecode' => 299,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 87,'code' => 'GD','name' => "Grenada",'phonecode' => 1473,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 88,'code' => 'GP','name' => "Guadeloupe",'phonecode' => 590,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 89,'code' => 'GU','name' => "Guam",'phonecode' => 1671,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 90,'code' => 'GT','name' => "Guatemala",'phonecode' => 502,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 91,'code' => 'XU','name' => "Guernsey and Alderney",'phonecode' => 44,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 92,'code' => 'GN','name' => "Guinea",'phonecode' => 224,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 93,'code' => 'GW','name' => "Guinea-Bissau",'phonecode' => 245,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 94,'code' => 'GY','name' => "Guyana",'phonecode' => 592,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 95,'code' => 'HT','name' => "Haiti",'phonecode' => 509,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 96,'code' => 'HM','name' => "Heard and McDonald Islands",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 97,'code' => 'HN','name' => "Honduras",'phonecode' => 504,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 98,'code' => 'HK','name' => "Hong Kong S.A.R.",'phonecode' => 852,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 99,'code' => 'HU','name' => "Hungary",'phonecode' => 36,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 100,'code' => 'IS','name' => "Iceland",'phonecode' => 354,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 101,'code' => 'IN','name' => "India",'phonecode' => 91,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 102,'code' => 'ID','name' => "Indonesia",'phonecode' => 62,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 103,'code' => 'IR','name' => "Iran",'phonecode' => 98,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 104,'code' => 'IQ','name' => "Iraq",'phonecode' => 964,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 105,'code' => 'IE','name' => "Ireland",'phonecode' => 353,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 106,'code' => 'IL','name' => "Israel",'phonecode' => 972,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 107,'code' => 'IT','name' => "Italy",'phonecode' => 39,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 108,'code' => 'JM','name' => "Jamaica",'phonecode' => 1876,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 109,'code' => 'JP','name' => "Japan",'phonecode' => 81,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 110,'code' => 'XJ','name' => "Jersey",'phonecode' => 44,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 111,'code' => 'JO','name' => "Jordan",'phonecode' => 962,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 112,'code' => 'KZ','name' => "Kazakhstan",'phonecode' => 7,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 113,'code' => 'KE','name' => "Kenya",'phonecode' => 254,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 114,'code' => 'KI','name' => "Kiribati",'phonecode' => 686,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 115,'code' => 'KP','name' => "Korea North",'phonecode' => 850,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 116,'code' => 'KR','name' => "Korea South",'phonecode' => 82,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 117,'code' => 'KW','name' => "Kuwait",'phonecode' => 965,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 118,'code' => 'KG','name' => "Kyrgyzstan",'phonecode' => 996,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 119,'code' => 'LA','name' => "Laos",'phonecode' => 856,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 120,'code' => 'LV','name' => "Latvia",'phonecode' => 371,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 121,'code' => 'LB','name' => "Lebanon",'phonecode' => 961,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 122,'code' => 'LS','name' => "Lesotho",'phonecode' => 266,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 123,'code' => 'LR','name' => "Liberia",'phonecode' => 231,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 124,'code' => 'LY','name' => "Libya",'phonecode' => 218,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 125,'code' => 'LI','name' => "Liechtenstein",'phonecode' => 423,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 126,'code' => 'LT','name' => "Lithuania",'phonecode' => 370,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 127,'code' => 'LU','name' => "Luxembourg",'phonecode' => 352,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 128,'code' => 'MO','name' => "Macau S.A.R.",'phonecode' => 853,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 129,'code' => 'MK','name' => "Macedonia",'phonecode' => 389,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 130,'code' => 'MG','name' => "Madagascar",'phonecode' => 261,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 131,'code' => 'MW','name' => "Malawi",'phonecode' => 265,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 132,'code' => 'MY','name' => "Malaysia",'phonecode' => 60,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 133,'code' => 'MV','name' => "Maldives",'phonecode' => 960,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 134,'code' => 'ML','name' => "Mali",'phonecode' => 223,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 135,'code' => 'MT','name' => "Malta",'phonecode' => 356,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 136,'code' => 'XM','name' => "Man (Isle of)",'phonecode' => 44,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 137,'code' => 'MH','name' => "Marshall Islands",'phonecode' => 692,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 138,'code' => 'MQ','name' => "Martinique",'phonecode' => 596,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 139,'code' => 'MR','name' => "Mauritania",'phonecode' => 222,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 140,'code' => 'MU','name' => "Mauritius",'phonecode' => 230,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 141,'code' => 'YT','name' => "Mayotte",'phonecode' => 269,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 142,'code' => 'MX','name' => "Mexico",'phonecode' => 52,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 143,'code' => 'FM','name' => "Micronesia",'phonecode' => 691,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 144,'code' => 'MD','name' => "Moldova",'phonecode' => 373,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 145,'code' => 'MC','name' => "Monaco",'phonecode' => 377,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 146,'code' => 'MN','name' => "Mongolia",'phonecode' => 976,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 147,'code' => 'MS','name' => "Montserrat",'phonecode' => 1664,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 148,'code' => 'MA','name' => "Morocco",'phonecode' => 212,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 149,'code' => 'MZ','name' => "Mozambique",'phonecode' => 258,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 150,'code' => 'MM','name' => "Myanmar",'phonecode' => 95,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 151,'code' => 'NA','name' => "Namibia",'phonecode' => 264,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 152,'code' => 'NR','name' => "Nauru",'phonecode' => 674,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 153,'code' => 'NP','name' => "Nepal",'phonecode' => 977,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 154,'code' => 'AN','name' => "Netherlands Antilles",'phonecode' => 599,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 155,'code' => 'NL','name' => "Netherlands The",'phonecode' => 31,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 156,'code' => 'NC','name' => "New Caledonia",'phonecode' => 687,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 157,'code' => 'NZ','name' => "New Zealand",'phonecode' => 64,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 158,'code' => 'NI','name' => "Nicaragua",'phonecode' => 505,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 159,'code' => 'NE','name' => "Niger",'phonecode' => 227,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 160,'code' => 'NG','name' => "Nigeria",'phonecode' => 234,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 161,'code' => 'NU','name' => "Niue",'phonecode' => 683,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 162,'code' => 'NF','name' => "Norfolk Island",'phonecode' => 672,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 163,'code' => 'MP','name' => "Northern Mariana Islands",'phonecode' => 1670,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 164,'code' => 'NO','name' => "Norway",'phonecode' => 47,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 165,'code' => 'OM','name' => "Oman",'phonecode' => 968,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 166,'code' => 'PK','name' => "Pakistan",'phonecode' => 92,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 167,'code' => 'PW','name' => "Palau",'phonecode' => 680,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 168,'code' => 'PS','name' => "Palestinian Territory Occupied",'phonecode' => 970,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 169,'code' => 'PA','name' => "Panama",'phonecode' => 507,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 170,'code' => 'PG','name' => "Papua new Guinea",'phonecode' => 675,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 171,'code' => 'PY','name' => "Paraguay",'phonecode' => 595,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 172,'code' => 'PE','name' => "Peru",'phonecode' => 51,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 173,'code' => 'PH','name' => "Philippines",'phonecode' => 63,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 174,'code' => 'PN','name' => "Pitcairn Island",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 175,'code' => 'PL','name' => "Poland",'phonecode' => 48,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 176,'code' => 'PT','name' => "Portugal",'phonecode' => 351,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 177,'code' => 'PR','name' => "Puerto Rico",'phonecode' => 1787,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 178,'code' => 'QA','name' => "Qatar",'phonecode' => 974,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 179,'code' => 'RE','name' => "Reunion",'phonecode' => 262,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 180,'code' => 'RO','name' => "Romania",'phonecode' => 40,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 181,'code' => 'RU','name' => "Russia",'phonecode' => 70,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 182,'code' => 'RW','name' => "Rwanda",'phonecode' => 250,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 183,'code' => 'SH','name' => "Saint Helena",'phonecode' => 290,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 184,'code' => 'KN','name' => "Saint Kitts And Nevis",'phonecode' => 1869,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 185,'code' => 'LC','name' => "Saint Lucia",'phonecode' => 1758,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 186,'code' => 'PM','name' => "Saint Pierre and Miquelon",'phonecode' => 508,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 187,'code' => 'VC','name' => "Saint Vincent And The Grenadines",'phonecode' => 1784,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 188,'code' => 'WS','name' => "Samoa",'phonecode' => 684,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 189,'code' => 'SM','name' => "San Marino",'phonecode' => 378,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 190,'code' => 'ST','name' => "Sao Tome and Principe",'phonecode' => 239,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 191,'code' => 'SA','name' => "Saudi Arabia",'phonecode' => 966,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 192,'code' => 'SN','name' => "Senegal",'phonecode' => 221,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 193,'code' => 'RS','name' => "Serbia",'phonecode' => 381,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 194,'code' => 'SC','name' => "Seychelles",'phonecode' => 248,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 195,'code' => 'SL','name' => "Sierra Leone",'phonecode' => 232,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 196,'code' => 'SG','name' => "Singapore",'phonecode' => 65,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 197,'code' => 'SK','name' => "Slovakia",'phonecode' => 421,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 198,'code' => 'SI','name' => "Slovenia",'phonecode' => 386,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 199,'code' => 'XG','name' => "Smaller Territories of the UK",'phonecode' => 44,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 200,'code' => 'SB','name' => "Solomon Islands",'phonecode' => 677,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 201,'code' => 'SO','name' => "Somalia",'phonecode' => 252,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 202,'code' => 'ZA','name' => "South Africa",'phonecode' => 27,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 203,'code' => 'GS','name' => "South Georgia",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 204,'code' => 'SS','name' => "South Sudan",'phonecode' => 211,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 205,'code' => 'ES','name' => "Spain",'phonecode' => 34,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 206,'code' => 'LK','name' => "Sri Lanka",'phonecode' => 94,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 207,'code' => 'SD','name' => "Sudan",'phonecode' => 249,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 208,'code' => 'SR','name' => "Suriname",'phonecode' => 597,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 209,'code' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'phonecode' => 47,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 210,'code' => 'SZ','name' => "Swaziland",'phonecode' => 268,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 211,'code' => 'SE','name' => "Sweden",'phonecode' => 46,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 212,'code' => 'CH','name' => "Switzerland",'phonecode' => 41,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 213,'code' => 'SY','name' => "Syria",'phonecode' => 963,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 214,'code' => 'TW','name' => "Taiwan",'phonecode' => 886,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 215,'code' => 'TJ','name' => "Tajikistan",'phonecode' => 992,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 216,'code' => 'TZ','name' => "Tanzania",'phonecode' => 255,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 217,'code' => 'TH','name' => "Thailand",'phonecode' => 66,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 218,'code' => 'TG','name' => "Togo",'phonecode' => 228,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 219,'code' => 'TK','name' => "Tokelau",'phonecode' => 690,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 220,'code' => 'TO','name' => "Tonga",'phonecode' => 676,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 221,'code' => 'TT','name' => "Trinidad And Tobago",'phonecode' => 1868,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 222,'code' => 'TN','name' => "Tunisia",'phonecode' => 216,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 223,'code' => 'TR','name' => "Turkey",'phonecode' => 90,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 224,'code' => 'TM','name' => "Turkmenistan",'phonecode' => 7370,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 225,'code' => 'TC','name' => "Turks And Caicos Islands",'phonecode' => 1649,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 226,'code' => 'TV','name' => "Tuvalu",'phonecode' => 688,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 227,'code' => 'UG','name' => "Uganda",'phonecode' => 256,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 228,'code' => 'UA','name' => "Ukraine",'phonecode' => 380,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 229,'code' => 'AE','name' => "United Arab Emirates",'phonecode' => 971,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 230,'code' => 'GB','name' => "United Kingdom",'phonecode' => 44,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 231,'code' => 'US','name' => "United States",'phonecode' => 1,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 232,'code' => 'UM','name' => "United States Minor Outlying Islands",'phonecode' => 1,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 233,'code' => 'UY','name' => "Uruguay",'phonecode' => 598,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 234,'code' => 'UZ','name' => "Uzbekistan",'phonecode' => 998,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 235,'code' => 'VU','name' => "Vanuatu",'phonecode' => 678,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 236,'code' => 'VA','name' => "Vatican City State (Holy See)",'phonecode' => 39,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 237,'code' => 'VE','name' => "Venezuela",'phonecode' => 58,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 238,'code' => 'VN','name' => "Vietnam",'phonecode' => 84,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 239,'code' => 'VG','name' => "Virgin Islands (British)",'phonecode' => 1284,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 240,'code' => 'VI','name' => "Virgin Islands (US)",'phonecode' => 1340,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 241,'code' => 'WF','name' => "Wallis And Futuna Islands",'phonecode' => 681,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 242,'code' => 'EH','name' => "Western Sahara",'phonecode' => 212,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 243,'code' => 'YE','name' => "Yemen",'phonecode' => 967,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 244,'code' => 'YU','name' => "Yugoslavia",'phonecode' => 38,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 245,'code' => 'ZM','name' => "Zambia",'phonecode' => 260,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            array('id' => 246,'code' => 'ZW','name' => "Zimbabwe",'phonecode' => 263,'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
            );
            DB::table('countries')->insert($countries);
    }
}
