// eslint-disable-next-line import/no-anonymous-default-export
export default {
  isAuth: false,
  isSubmitting: false,
  isFetching: false,
  userInfo: {},
  setting: {},
  homePageData: {},
  pageData: {},
  userParams: {},
  investmentCapital: [],
  plan: [],
  userDashbord: {},
  statement: [],
  passbook: [],
  notification: [],
  order: [],
  holding: [],
  holdingList: {},
  walletAmount: 0,
}
